### ISSUE TITLE
sd_hash missing in payload of Key Binding JWT

### ISSUE THREAD

**Issue by gmirc12** [Meeco/sd-jwt-vc#18]
According to spec [Key Binding for SD-JWT-VC](https://www.ietf.org/archive/id/draft-ietf-oauth-sd-jwt-vc-01.html#name-key-binding-jwt), 

> the Key Binding JWT MUST adhere to the rules defined in Section 5.3 of [SD-JWT spec](https://www.ietf.org/archive/id/draft-ietf-oauth-selective-disclosure-jwt-07.html#section-5.3-3.2.1)

This means, that the sd_hash claim has to be included in the payload of the Key Binding JWT. 

The code has to be refactored to calculate and add the sd_hash claim in the payload of the Key Binding JWT.

**Comment by gmirc12** [comment]
Suggested PR: #19

**Comment by ragnika** [comment]
PR #19 merged

**Comment by ragnika** [comment]
PR https://github.com/Meeco/sd-jwt-vc/pull/19 merged
