### ISSUE TITLE
`iat` claim has wrong value

### ISSUE THREAD

**Issue by javereec** [Meeco/sd-jwt-vc#23]
See:

https://github.com/Meeco/sd-jwt-vc/blob/f130c2787b847a2f75ba374babfc40b0ed0c6f8f/src/holder.ts#L73

Check other values also and make sure we convert milliseconds to seconds where appropriate (using something like `Math.floor(Date.now() / 1000)`

**Comment by vijayshiyani** [comment]
FYI
The issue has been addressed in the latest version, 1.0.2, of the @meeco/sd-jwt-vc package. You can find the fixed version at the following link: [Version 1.0.2 on npm](https://www.npmjs.com/package/@meeco/sd-jwt-vc/v/1.0.2).
